# Generated by Selenium IDE
import pytest
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from group import Group

class TestLoginandaddanewgroup(unittest.TestCase):
    def setup_method(self, method):
        self.wd = webdriver.Chrome()
        self.vars = {}

    def test_login_and_add_new_group_as_admin(self):
        wd = self.wd
        self.open_home_page(wd)
        self.login(wd, username="admin", password="secret")
        self.open_groups_page(wd)
        self.create_group(wd, Group(group_name="first_new_group", group_header="header", group_footer="footer"))
        self.return_to_groups_page(wd)
        self.logout(wd)

    def test_login_and_add_new_group_empty_header(self):
        wd = self.wd
        self.open_home_page(wd)
        self.login(wd, username="admin", password="secret")
        self.open_groups_page(wd)
        self.create_group(wd, Group(group_name="Super_name", group_header="", group_footer="Text"))
        self.return_to_groups_page(wd)
        self.logout(wd)

    def open_home_page(self, wd):
        wd.get("http://192.168.64.2/addressbook/")
        wd.set_window_size(1280, 731)

    def login(self, wd, username, password):
        wd.find_element(By.NAME, "user").send_keys(username)
        wd.find_element(By.NAME, "pass").send_keys(password)
        wd.find_element(By.XPATH, "//input[@value=\'Login\']").click()

    def open_groups_page(self, wd):
        wd.find_element(By.LINK_TEXT, "groups").click()

    def create_group(self, wd, group):
        # init group creation
        wd.find_element(By.NAME, "new").click()
        # fill group form
        wd.find_element(By.NAME, "group_name").click()
        wd.find_element(By.NAME, "group_name").send_keys(group.group_name)
        wd.find_element(By.NAME, "group_header").click()
        wd.find_element(By.NAME, "group_header").send_keys(group.group_header)
        wd.find_element(By.NAME, "group_footer").click()
        wd.find_element(By.NAME, "group_footer").send_keys(group.group_footer)
        # submit group creation
        wd.find_element(By.NAME, "submit").click()

    def return_to_groups_page(self, wd):
        wd.find_element(By.LINK_TEXT, "groups").click()

    def logout(self, wd):
        wd.find_element(By.LINK_TEXT, "Logout").click()

    def teardown_method(self, method):
        self.wd.quit()


if __name__ == '__main__':
    unittest.main()

